### PR TITLE
Add a guide for GH read-only triggers

### PR DESCRIPTION
**Pull request by josephschorr**

### CODE REVIEW

**Comment by jzelinskie** [comment]
- link to the GH docs for revoking oauth
- I'm pretty sure after revoking oauth, you have to manually add back the deploy key

**Comment by jzelinskie** [comment]
I'm hesitant to merge this until we've resolved all of the issues that `nickjj` has been reporting via IRC. He said he still can't delete a trigger. Did we deploy HEAD the other day?

**Comment by josephschorr** [comment]
We did, but I sent you another PR today to fix the deletion, so we can definitely wait on this

**Comment by jzelinskie** [comment]
We probably should've merged this a month ago.

**Pull request merged**
